# This file provides instructions for packaging.

`MooseX-ErsatzMethod`
	perl_version_from m`MooseX::ErsatzMethod`;
	version_from      m`MooseX::ErsatzMethod`;
	readme_from       m`MooseX::ErsatzMethod`;
	test_requires     p`Test::More 0.61`;
	requires          p`thanks`;
	requires          p`Moose 2.00`;
	.

