# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#> .

`MooseX-ErsatzMethod`
	:test-requirement       [ :on "Test::More 0.61"^^:CpanId ];
	:runtime-requirement    [ :on "Moose 2.00"^^:CpanId ];
	:runtime-requirement    [ :on "Module::Runtime"^^:CpanId ].

